---
driver:
  name: ec2
  aws_ssh_key_id: atanasc
  #security_group_ids: ["sg-8caa60e1"]
  region: us-east-2
  #availability_zone: b
  instance_type: t2.micro
  associate_public_ip: true
 
provisioner:
  name: shell

transport:
  ssh_key: "~/.ssh/id_rsa"
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

platforms:
  - name: ubuntu-xenial
    driver:
      image_id: ami-0352bc96e72c69d2d

verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
